/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResultView.java
 *
 * Created on Nov 30, 2011, 10:20:10 AM
 */
package uRead;

/**
 *
 * @author tigospodinova
 */
public class ResultView extends javax.swing.JPanel {

    Book book;
    /** Creates new form ResultView */
    public ResultView(SearchResult result) {
        initComponents();
        this.book = result.book();
        this.lblTitle.setText(book.getTitle());
        this.lblAuthor.setText(book.getAuthor());
        this.lblISBN.setText(book.getISBN10());
        this.lblDescription.setText(book.getDescription());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(uRead.UReadApp.class).getContext().getResourceMap(ResultView.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        lblTitle.setText(resourceMap.getString("lblTitle.text")); // NOI18N
        lblTitle.setName("lblTitle"); // NOI18N

        lblAuthor.setText(resourceMap.getString("lblAuthor.text")); // NOI18N
        lblAuthor.setName("lblAuthor"); // NOI18N

        lblISBN.setText(resourceMap.getString("lblISBN.text")); // NOI18N
        lblISBN.setName("lblISBN"); // NOI18N

        lblDescription.setText(resourceMap.getString("lblDescription.text")); // NOI18N
        lblDescription.setName("lblDescription"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(lblTitle)
                .add(61, 61, 61)
                .add(lblAuthor)
                .add(72, 72, 72)
                .add(lblISBN)
                .add(78, 78, 78)
                .add(lblDescription)
                .add(37, 37, 37)
                .add(jButton1)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblTitle)
                    .add(lblAuthor)
                    .add(lblISBN)
                    .add(lblDescription)
                    .add(jButton1))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
