
package uread;

import java.lang.String;
import java.util.ArrayList;

/** Represents the result set generated by a search query on a {@link BookDatabase}. */
public class SearchResults {

/** Never create this yourself, always use {@link BookDatabase#search}.
*/	public SearchResults() { fields=0; query=null; results=null; }

/** Returns the fields searched to generate these results.
  * A sum of at least one of {@link BookDatabase#S_TITLE}, {@link BookDatabase#S_AUTHOR}, and
  * {@link BookDatabase#S_ISBN}.
@return A sum of at least one of {@link BookDatabase#S_TITLE}, {@link BookDatabase#S_AUTHOR}, and {@link BookDatabase#S_ISBN}.
*/	public int fields() { return fields; }

/** Returns the search query string used to generate these results.
@return The search query string used to generate these results.
*/	public String query() { return query; }

/** Returns the number of {@link SearchResult}s found.
@return The number of {@link SearchResult}s found
*/	public int count() { return results.size(); }

/** Gets one particular result.
@param index Which {@link SearchResult} to get, valid from 0 to {@link #count()}-1 (inclusive)
@return The specified {@link SearchResult}
*/	public SearchResult get( int index ) { return results.get( index ); }

	private int fields;
	private String query;
	private ArrayList<SearchResult> results;
}

